---
apiVersion: v1
kind: Pod
metadata:
  name: model-runner
  labels:
    app: model-runner
spec:
  containers:
    - name: model-runner
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: model-runner
spec:
  selector:
    app: model-runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: model-runner
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  #tls:
  #    - hosts:
  #        - www.example.com
  #      secretName: example-tls